/**
 * Significant-weeks index: deterministic ranking of notable weeks in the
 * current term, derived from weekly_aggregates convergence statuses. Ranking
 * and links use no AI; a one-line display headline per week is generated by a
 * small model at recompute time (see significant-weeks-headlines.ts) and
 * degrades to null without affecting the index.
 *
 * Recomputed whenever the living term summary regenerates (aggregate data
 * changed), so the stored index is always consistent with the narrative.
 * Grounds the term-summary prompt and renders as /weekly/<date> links.
 */

import { asc, gte, sql } from 'drizzle-orm';
import { T2_INAUGURATION } from '@/lib/data/analysis-periods';
import { CATEGORIES } from '@/lib/data/categories';
import { getDb, isDbAvailable } from '@/lib/db';
import { significantWeeks, weeklyAggregates } from '@/lib/db/schema';

export interface WeekStatusRow {
  weekOf: string;
  category: string;
  status: string | null;
}

export interface SignificantWeekReason {
  type: 'peak_concern' | 'concern_spike' | 'new_concern' | 'monitoring_began';
  detail: string;
}

export interface SignificantWeek {
  weekOf: string;
  reasons: SignificantWeekReason[];
  /** One-line AI event summary (null when unavailable — display falls back to reasons). */
  headline?: string | null;
  rank: number;
}

export const MAX_SIGNIFICANT_WEEKS = 12;
const CONFIRMED = 'ConfirmedConcern';
/** A spike week needs at least this many categories at ConfirmedConcern. */
const SPIKE_MIN_CONFIRMED = 3;
/** A category re-entering ConfirmedConcern counts as new after this many weeks below. */
const REENTRY_GAP_WEEKS = 4;

const PEAK_SCORE = 100;
const SPIKE_SCORE_PER_CATEGORY = 5;
const NEW_CONCERN_SCORE = 10;
/**
 * Score for the inauguration bootstrap entry (#585): week one auto-qualifies
 * every confirmed category as "new" (weeksBelow starts at Infinity), which is
 * monitoring cold-start, not detection — it must never outrank real events
 * (peak = 100, spikes/new-concerns compound), but stays findable.
 */
const MONITORING_BEGAN_SCORE = 20;

function categoryTitle(key: string): string {
  return CATEGORIES.find((c) => c.key === key)?.title ?? key;
}

/** Count categories at ConfirmedConcern per week, sorted by week ascending. */
function confirmedCountsByWeek(rows: WeekStatusRow[]): Map<string, number> {
  const counts = new Map<string, number>();
  for (const row of rows) {
    if (!counts.has(row.weekOf)) counts.set(row.weekOf, 0);
    if (row.status === CONFIRMED) counts.set(row.weekOf, (counts.get(row.weekOf) ?? 0) + 1);
  }
  return new Map([...counts.entries()].sort(([a], [b]) => a.localeCompare(b)));
}

function median(values: number[]): number {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0 ? (sorted[mid - 1] + sorted[mid]) / 2 : sorted[mid];
}

/** The single week with the most categories at ConfirmedConcern (tie → most recent). */
function findPeakWeek(counts: Map<string, number>): { weekOf: string; count: number } | null {
  let peak: { weekOf: string; count: number } | null = null;
  for (const [weekOf, count] of counts) {
    if (count > 0 && (!peak || count >= peak.count)) peak = { weekOf, count };
  }
  return peak;
}

/** Weeks whose confirmed count is both ≥ SPIKE_MIN_CONFIRMED and ≥ 2× the nonzero median. */
function findSpikeWeeks(counts: Map<string, number>): Map<string, number> {
  const nonzero = [...counts.values()].filter((c) => c > 0);
  const threshold = Math.max(SPIKE_MIN_CONFIRMED, 2 * median(nonzero));
  const spikes = new Map<string, number>();
  for (const [weekOf, count] of counts) {
    if (count >= threshold) spikes.set(weekOf, count);
  }
  return spikes;
}

/**
 * Weeks where a category entered ConfirmedConcern — first time in the term,
 * or re-entry after ≥ REENTRY_GAP_WEEKS weeks below it.
 */
function findNewConcerns(rows: WeekStatusRow[]): Map<string, string[]> {
  const byCategory = new Map<string, WeekStatusRow[]>();
  for (const row of rows) {
    if (!byCategory.has(row.category)) byCategory.set(row.category, []);
    byCategory.get(row.category)!.push(row);
  }

  const entries = new Map<string, string[]>();
  for (const [category, catRows] of byCategory) {
    const sorted = [...catRows].sort((a, b) => a.weekOf.localeCompare(b.weekOf));
    let weeksBelow = Infinity; // start of term counts as a long gap
    for (const row of sorted) {
      if (row.status === CONFIRMED) {
        if (weeksBelow >= REENTRY_GAP_WEEKS) {
          if (!entries.has(row.weekOf)) entries.set(row.weekOf, []);
          entries.get(row.weekOf)!.push(category);
        }
        weeksBelow = 0;
      } else {
        weeksBelow++;
      }
    }
  }
  return entries;
}

/** Rank notable weeks by deterministic rules; capped at `cap`. Pure. */
export function rankSignificantWeeks(
  rows: WeekStatusRow[],
  cap = MAX_SIGNIFICANT_WEEKS,
): SignificantWeek[] {
  const counts = confirmedCountsByWeek(rows);
  const totalCategories = new Set(rows.map((r) => r.category)).size;

  const candidates = new Map<string, { score: number; reasons: SignificantWeekReason[] }>();
  const add = (weekOf: string, score: number, reason: SignificantWeekReason) => {
    if (!candidates.has(weekOf)) candidates.set(weekOf, { score: 0, reasons: [] });
    const entry = candidates.get(weekOf)!;
    entry.score += score;
    entry.reasons.push(reason);
  };

  const peak = findPeakWeek(counts);
  if (peak) {
    add(peak.weekOf, PEAK_SCORE, {
      type: 'peak_concern',
      detail: `Peak concern: ${peak.count} of ${totalCategories} categories at Confirmed Concern`,
    });
  }

  for (const [weekOf, count] of findSpikeWeeks(counts)) {
    if (weekOf === peak?.weekOf) continue; // peak already covers it
    add(weekOf, count * SPIKE_SCORE_PER_CATEGORY, {
      type: 'concern_spike',
      detail: `${count} categories at Confirmed Concern`,
    });
  }

  for (const [weekOf, categories] of findNewConcerns(rows)) {
    if (weekOf === T2_INAUGURATION) {
      add(weekOf, MONITORING_BEGAN_SCORE, {
        type: 'monitoring_began',
        detail: 'Monitoring began — initial category statuses assigned',
      });
      continue;
    }
    const titles = categories.map(categoryTitle).sort();
    add(weekOf, categories.length * NEW_CONCERN_SCORE, {
      type: 'new_concern',
      detail: `${titles.join(', ')} entered Confirmed Concern`,
    });
  }

  return [...candidates.entries()]
    .sort(([weekA, a], [weekB, b]) => b.score - a.score || weekB.localeCompare(weekA))
    .slice(0, cap)
    .map(([weekOf, { reasons }], i) => ({ weekOf, reasons, rank: i + 1 }));
}

/** Load per-category-week convergence statuses for the current term. */
async function loadTermStatusRows(): Promise<WeekStatusRow[]> {
  const db = getDb();
  const rows = await db
    .select({
      weekOf: weeklyAggregates.weekOf,
      category: weeklyAggregates.category,
      status: sql<string | null>`${weeklyAggregates.convergenceDetail}->>'status'`,
    })
    .from(weeklyAggregates)
    .where(gte(weeklyAggregates.weekOf, T2_INAUGURATION));
  return rows.map((r) => ({ ...r, weekOf: String(r.weekOf).slice(0, 10) }));
}

/**
 * Recompute and store the index (delete-all + insert). Ranking is deterministic;
 * a one-line AI headline per week is generated for display (null on failure).
 * Returns the new list.
 */
export async function recomputeSignificantWeeks(): Promise<SignificantWeek[]> {
  if (!isDbAvailable()) return [];
  const ranked = rankSignificantWeeks(await loadTermStatusRows());

  const { generateHeadlines } = await import('./significant-weeks-headlines');
  const headlines = await generateHeadlines(ranked);
  const withHeadlines = ranked.map((w) => ({
    ...w,
    headline: headlines.get(w.weekOf) ?? null,
  }));

  const db = getDb();
  await db.transaction(async (tx) => {
    await tx.delete(significantWeeks);
    if (withHeadlines.length > 0) {
      await tx.insert(significantWeeks).values(withHeadlines);
    }
  });
  console.log(`[significant-weeks] Recomputed: ${withHeadlines.length} weeks indexed`);
  return withHeadlines;
}

/** Read the stored index, most significant first. */
export async function getSignificantWeeks(): Promise<SignificantWeek[]> {
  if (!isDbAvailable()) return [];
  const db = getDb();
  const rows = await db.select().from(significantWeeks).orderBy(asc(significantWeeks.rank));
  return rows.map((r) => ({
    weekOf: String(r.weekOf).slice(0, 10),
    reasons: (r.reasons ?? []) as SignificantWeekReason[],
    headline: r.headline ?? null,
    rank: r.rank,
  }));
}
