name: Feature Request
description: Suggest an improvement or new capability
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for improving the dashboard? We'd love to hear it. Please describe the problem you're trying to solve, not just the solution you have in mind.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this solve, or what gap does it fill?
      placeholder: "There's no way to tell whether a category's status has changed over time."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work? Be as specific or as broad as you want.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you thought about and why they're less ideal.
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the project does this relate to?
      options:
        - Assessment methodology (keyword matching, scoring, thresholds)
        - Data sources (new feeds, APIs, scrapers)
        - AI analysis (prompts, debate, legal analysis)
        - UX / UI (dashboard layout, progressive disclosure, accessibility)
        - Infrastructure (caching, database, deployment)
        - Developer experience (testing, tooling, documentation)
        - Other
    validations:
      required: true
