import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import type { DigestEntry } from '@/lib/types/trends';

export default function DigestPage() {
  const router = useRouter();
  const { date } = router.query;
  const [digest, setDigest] = useState<DigestEntry | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!date || typeof date !== 'string') return;
    loadDigest(date);
  }, [date]);

  const loadDigest = async (dateStr: string) => {
    try {
      const res = await fetch(`/api/digest/${dateStr}`);
      if (res.ok) {
        setDigest(await res.json());
      } else {
        setError(`No digest found for ${dateStr}`);
      }
    } catch {
      setError('Failed to load digest');
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Head>
        <title>Digest {date} — Democracy Monitor</title>
      </Head>
      <main className="min-h-screen bg-slate-50 py-6 px-4 md:px-8">
        <div className="max-w-4xl mx-auto space-y-6">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-bold text-slate-900">Daily Digest — {date}</h1>
            <div className="flex gap-3">
              <Link href="/digest" className="text-sm text-blue-600 hover:underline">
                Archive
              </Link>
              <Link href="/" className="text-sm text-blue-600 hover:underline">
                Dashboard
              </Link>
            </div>
          </div>

          {loading && <p className="text-sm text-slate-500 italic">Loading digest...</p>}

          {error && (
            <div className="bg-white border border-slate-200 rounded-lg p-6 text-center">
              <p className="text-sm text-slate-500">{error}</p>
            </div>
          )}

          {digest && (
            <div className="bg-white border border-slate-200 rounded-lg p-6 space-y-4">
              <div className="flex items-center justify-between text-xs text-slate-500">
                <span>
                  Generated by {digest.provider} ({digest.model})
                </span>
                <span>{new Date(digest.createdAt).toLocaleString()}</span>
              </div>

              <section>
                <h2 className="text-lg font-semibold text-slate-900 mb-2">Summary</h2>
                <p className="text-sm text-slate-700">{digest.summary}</p>
              </section>

              {digest.highlights.length > 0 && (
                <section>
                  <h2 className="text-lg font-semibold text-slate-900 mb-2">Highlights</h2>
                  <ul className="space-y-1">
                    {digest.highlights.map((h, i) => (
                      <li key={i} className="text-sm text-slate-700">
                        {'•'} {h}
                      </li>
                    ))}
                  </ul>
                </section>
              )}

              {Object.keys(digest.categorySummaries).length > 0 && (
                <section>
                  <h2 className="text-lg font-semibold text-slate-900 mb-2">By Category</h2>
                  <div className="space-y-2">
                    {Object.entries(digest.categorySummaries).map(([cat, summary]) => (
                      <div key={cat} className="border border-slate-200 rounded p-3">
                        <h3 className="text-sm font-semibold text-slate-800">{cat}</h3>
                        <p className="text-xs text-slate-600 mt-1">{summary}</p>
                      </div>
                    ))}
                  </div>
                </section>
              )}

              {digest.overallAssessment && (
                <section className="pt-4 border-t border-slate-200">
                  <h2 className="text-lg font-semibold text-slate-900 mb-2">Overall Assessment</h2>
                  <p className="text-sm text-slate-700 italic">{digest.overallAssessment}</p>
                </section>
              )}
            </div>
          )}
        </div>
      </main>
    </>
  );
}
