import type { NextApiRequest, NextApiResponse } from 'next';

/**
 * Served at /.well-known/security.txt via a rewrite (#635, RFC 9116).
 *
 * Generated by a route rather than a static file so the required `Expires`
 * field is always ~11 months out — it can't silently lapse without a redeploy.
 * NOTE: the Contact address must route to a monitored inbox — update it if
 * `security@democracymonitor.us` isn't set up.
 */
export default function handler(_req: NextApiRequest, res: NextApiResponse): void {
  const expires = new Date();
  expires.setMonth(expires.getMonth() + 11);

  const body =
    [
      'Contact: mailto:security@democracymonitor.us',
      `Expires: ${expires.toISOString()}`,
      'Preferred-Languages: en',
      'Canonical: https://democracymonitor.us/.well-known/security.txt',
    ].join('\n') + '\n';

  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=86400');
  res.status(200).send(body);
}
