import type { ConcernLevel } from '@/lib/types/structural';

export interface KnownEvent {
  id: string;
  date: string;
  category: string;
  description: string;
  period: 'trump_t1' | 'biden_2021' | 'biden_2022' | 'trump_t2';
  expectedMinStatus: ConcernLevel;
  expectedLayers?: { l1?: boolean; l2?: boolean; l3?: boolean };
  expectedErosionType?: string;
  signalDensity?: 'strong' | 'moderate' | 'thin';
  notes?: string;
}

// --- Trump T1 (2017–2018) — Baseline Period Events ---
// These events define what "elevated within a baseline" looks like.
// The system isn't expected to flag baselines as concerning (baselines define normal),
// but these events should produce visible spikes vs Biden baseline periods.

export const TRUMP_T1_EVENTS: KnownEvent[] = [
  // T1-1. Travel Ban EO #1 (Jan 27, 2017)
  {
    id: 'T1-1',
    date: '2017-01-27',
    category: 'civilLiberties',
    description: 'Travel ban EO #1 (EO 13769)',
    period: 'trump_t1',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    expectedErosionType: 'formal_override',
    signalDensity: 'strong',
  },
  {
    id: 'T1-1',
    date: '2017-01-27',
    category: 'immigrationEnforcement',
    description: 'Travel ban EO #1 (EO 13769)',
    period: 'trump_t1',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    expectedErosionType: 'formal_override',
    signalDensity: 'strong',
  },
  {
    id: 'T1-1',
    date: '2017-01-27',
    category: 'judicialIndependence',
    description: 'Travel ban EO #1 — TRO filings',
    period: 'trump_t1',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true },
    signalDensity: 'moderate',
  },
  // T1-2. Comey Firing (May 9, 2017)
  {
    id: 'T1-2',
    date: '2017-05-09',
    category: 'executiveOversight',
    description: 'James Comey firing',
    period: 'trump_t1',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l2: true },
    expectedErosionType: 'institutional_capture',
    signalDensity: 'moderate',
  },
  {
    id: 'T1-2',
    date: '2017-05-09',
    category: 'judicialIndependence',
    description: 'James Comey firing — DOJ memos',
    period: 'trump_t1',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l2: true },
    signalDensity: 'moderate',
  },
  {
    id: 'T1-2',
    date: '2017-05-09',
    category: 'lawEnforcement',
    description: 'James Comey firing — FBI leadership removal',
    period: 'trump_t1',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l2: true },
    signalDensity: 'moderate',
  },
  // T1-3. Sessions Recusal Pressure (Feb–Mar 2017)
  // Expected miss — signal was in rhetoric, not formal government documents.
  {
    id: 'T1-3',
    date: '2017-03-02',
    category: 'judicialIndependence',
    description: 'Jeff Sessions recusal pressure',
    period: 'trump_t1',
    expectedMinStatus: 'Stable',
    signalDensity: 'thin',
    notes:
      'Expected miss — signal in presidential rhetoric, not formal documents. Validates rhetoric source gap.',
  },
  {
    id: 'T1-3',
    date: '2017-03-02',
    category: 'lawEnforcement',
    description: 'Jeff Sessions recusal pressure',
    period: 'trump_t1',
    expectedMinStatus: 'Stable',
    signalDensity: 'thin',
    notes: 'Expected miss — signal in presidential rhetoric, not formal documents.',
  },
  // T1-4. DACA Rescission (Sep 5, 2017)
  {
    id: 'T1-4',
    date: '2017-09-05',
    category: 'civilLiberties',
    description: 'DACA rescission',
    period: 'trump_t1',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    expectedErosionType: 'formal_override',
    signalDensity: 'strong',
  },
  {
    id: 'T1-4',
    date: '2017-09-05',
    category: 'immigrationEnforcement',
    description: 'DACA rescission',
    period: 'trump_t1',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    signalDensity: 'strong',
  },
  {
    id: 'T1-4',
    date: '2017-09-05',
    category: 'executiveActions',
    description: 'DACA rescission — AG Sessions memo',
    period: 'trump_t1',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l2: true },
    signalDensity: 'moderate',
  },
  // T1-5. Family Separation Policy (Apr 6, 2018)
  {
    id: 'T1-5',
    date: '2018-04-06',
    category: 'civilLiberties',
    description: 'Family separation policy — zero tolerance memo',
    period: 'trump_t1',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    expectedErosionType: 'formal_override',
    signalDensity: 'strong',
  },
  {
    id: 'T1-5',
    date: '2018-04-06',
    category: 'immigrationEnforcement',
    description: 'Family separation — DHS enforcement memos',
    period: 'trump_t1',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    signalDensity: 'strong',
  },
  {
    id: 'T1-5',
    date: '2018-04-06',
    category: 'lawEnforcement',
    description: 'Family separation — DOJ zero-tolerance memo',
    period: 'trump_t1',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l2: true },
    expectedErosionType: 'formal_override',
    signalDensity: 'moderate',
  },
];

// --- Trump T2 (Jan 20, 2025 – present) — Active Monitoring Period ---

export const TRUMP_T2_EVENTS: KnownEvent[] = [
  // T2-1. Day One EO Blitz (Jan 20, 2025)
  {
    id: 'T2-1',
    date: '2025-01-20',
    category: 'executiveActions',
    description: 'Day One EO blitz — 20-30 executive orders',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true, l3: true },
    signalDensity: 'strong',
  },
  {
    id: 'T2-1',
    date: '2025-01-20',
    category: 'civilService',
    description: 'Day One EO blitz — Schedule F reinstatement',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l2: true },
    expectedErosionType: 'formal_override',
    signalDensity: 'strong',
  },
  {
    id: 'T2-1',
    date: '2025-01-20',
    category: 'immigrationEnforcement',
    description: 'Day One EO blitz — immigration EOs',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    signalDensity: 'strong',
  },
  {
    id: 'T2-1',
    date: '2025-01-20',
    category: 'civilLiberties',
    description: 'Day One EO blitz — DEI order',
    period: 'trump_t2',
    expectedMinStatus: 'Stable',
    expectedLayers: { l2: true },
    signalDensity: 'moderate',
    notes:
      'Expected miss — DEI order signal thin in formal documents; requires rhetoric/media sources.',
  },
  // T2-2. Mass IG Firings (Jan 24, 2025)
  {
    id: 'T2-2',
    date: '2025-01-24',
    category: 'executiveOversight',
    description: 'Mass firing of 17 Inspectors General',
    period: 'trump_t2',
    expectedMinStatus: 'Divergent',
    expectedLayers: { l1: true, l2: true },
    expectedErosionType: 'institutional_capture',
    signalDensity: 'strong',
  },
  {
    id: 'T2-2',
    date: '2025-01-24',
    category: 'judicialIndependence',
    description: 'Mass IG firings — oversight removal',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l2: true },
    signalDensity: 'moderate',
  },
  // T2-3. DOGE/USAID Shutdown (Feb 3, 2025)
  {
    id: 'T2-3',
    date: '2025-02-03',
    category: 'executiveOversight',
    description: 'DOGE entry into USAID / agency shutdown',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true, l3: true },
    expectedErosionType: 'institutional_capture',
    signalDensity: 'strong',
  },
  {
    id: 'T2-3',
    date: '2025-02-03',
    category: 'executiveActions',
    description: 'DOGE/USAID — executive overreach',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    signalDensity: 'strong',
  },
  // T2-4. DOGE Treasury Access (Jan 27 / Feb 3, 2025)
  {
    id: 'T2-4',
    date: '2025-02-03',
    category: 'fiscal',
    description: 'DOGE access to Treasury payment systems',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l2: true },
    signalDensity: 'thin',
    notes: 'Thin signal — 1-2 court filings + media. L1 may be quiet; do not penalize.',
  },
  // T2-5. Deferred Resignation / Mass Layoffs (Jan 27, 2025 +)
  {
    id: 'T2-5',
    date: '2025-01-27',
    category: 'civilService',
    description: 'Deferred resignation program / mass federal layoffs',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true, l3: true },
    expectedErosionType: 'procedural_manipulation',
    signalDensity: 'strong',
  },
  // T2-6. Probationary Employee Mass Firing (Feb 10, 2025)
  {
    id: 'T2-6',
    date: '2025-02-10',
    category: 'civilService',
    description: 'Probationary employee mass firing — OPM directive',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    expectedErosionType: 'procedural_manipulation',
    signalDensity: 'strong',
  },
  // T2-7. Schedule F — multi-stage (3 dates)
  {
    id: 'T2-7',
    date: '2025-01-20',
    category: 'civilService',
    description: 'Schedule F reinstatement — executive order',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l2: true },
    expectedErosionType: 'formal_override',
    signalDensity: 'moderate',
    notes: 'Jan 20 EO may be buried in the Day One blitz.',
  },
  {
    id: 'T2-7',
    date: '2025-04-15',
    category: 'civilService',
    description: 'Schedule F — proposed rule (40K comments)',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    expectedErosionType: 'formal_override',
    signalDensity: 'strong',
  },
  {
    id: 'T2-7',
    date: '2026-02-06',
    category: 'civilService',
    description: 'Schedule F — final rule published in FR',
    period: 'trump_t2',
    expectedMinStatus: 'Divergent',
    expectedLayers: { l1: true, l2: true, l3: true },
    expectedErosionType: 'formal_override',
    signalDensity: 'strong',
  },
  // T2-8. DOJ Career Official Firings (Feb 2025)
  {
    id: 'T2-8',
    date: '2025-02-10',
    category: 'lawEnforcement',
    description: 'DOJ career official firings',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    expectedErosionType: 'selective_enforcement',
    signalDensity: 'moderate',
  },
  {
    id: 'T2-8',
    date: '2025-02-10',
    category: 'judicialIndependence',
    description: 'DOJ career official firings — justice system impact',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l2: true },
    signalDensity: 'moderate',
  },
  // T2-9. CISA Election Security Office Elimination (2025)
  {
    id: 'T2-9',
    date: '2025-06-01',
    category: 'elections',
    description: 'CISA election security office elimination',
    period: 'trump_t2',
    expectedMinStatus: 'Stable',
    expectedLayers: { l1: true },
    signalDensity: 'thin',
    notes:
      'Expected miss — thin signal, primarily institutional silence + media. No formal FR document may exist.',
  },
  {
    id: 'T2-9',
    date: '2025-06-01',
    category: 'infoAvailability',
    description: 'CISA election security — information gap',
    period: 'trump_t2',
    expectedMinStatus: 'Stable',
    signalDensity: 'thin',
    notes: 'May not be detected in infoAvailability if no formal document was published.',
  },
  // T2-10. Foreign Aid Freeze / Rescissions Act
  {
    id: 'T2-10',
    date: '2025-01-20',
    category: 'executiveActions',
    description: 'Foreign aid freeze EO',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l2: true },
    expectedErosionType: 'formal_override',
    signalDensity: 'strong',
    notes: 'Covered by T2-1 Day One EO blitz week.',
  },
  {
    id: 'T2-10',
    date: '2025-05-01',
    category: 'fiscal',
    description: 'Foreign aid rescission request ($9.4B)',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    expectedErosionType: 'formal_override',
    signalDensity: 'moderate',
  },
  {
    id: 'T2-10',
    date: '2025-08-01',
    category: 'fiscal',
    description: 'Rescissions Act passed',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true },
    signalDensity: 'moderate',
  },
  // T2-11. SCOTUS Allows Mass Layoffs (Jul 7, 2025)
  {
    id: 'T2-11',
    date: '2025-07-07',
    category: 'judicialIndependence',
    description: 'SCOTUS allows mass layoffs to proceed',
    period: 'trump_t2',
    expectedMinStatus: 'Stable',
    expectedLayers: { l2: true },
    signalDensity: 'moderate',
    notes:
      'Expected miss — SCOTUS ruling signal may not appear in judicialIndependence formal documents.',
  },
  {
    id: 'T2-11',
    date: '2025-07-07',
    category: 'civilService',
    description: 'SCOTUS mass layoffs decision — civil service impact',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l2: true },
    signalDensity: 'moderate',
  },
  // T2-12. Government Shutdown (Fall 2025)
  {
    id: 'T2-12',
    date: '2025-10-01',
    category: 'fiscal',
    description: 'Government shutdown',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true, l2: true },
    signalDensity: 'moderate',
  },
  {
    id: 'T2-12',
    date: '2025-10-01',
    category: 'civilService',
    description: 'Government shutdown — workforce impact',
    period: 'trump_t2',
    expectedMinStatus: 'Elevated',
    expectedLayers: { l1: true },
    signalDensity: 'moderate',
  },
];

export const ALL_KNOWN_EVENTS: KnownEvent[] = [...TRUMP_T1_EVENTS, ...TRUMP_T2_EVENTS];
